import type { Metadata } from 'next';
import ReduxProvider from '@/redux/provider';
import './globals.css';
import Header from '@/components/header';
import NavBar from '@/components/NavBar';
import Providers from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Header />
          <NavBar />
          <Providers>
            <div className="align-element py-20">{children}</div>
          </Providers>
        </ReduxProvider>
      </body>
    </html>
  );
}
